import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="flex flex-col justify-between min-h-screen items-center">
				<header className="p-4">
					<h2 className="text-4xl text-red-500">Hello I am Rich</h2>
				</header>
				{children}
				<footer className="p-4">
					<h4 className="text-xl text-red-500">&copy; R-Saunders</h4>
				</footer>
			</body>
		</html>
	);
}
